export default {
    color: {
        base: '#fff',
        light: '#767676',
        lightest: '#ccc',
        link: '#2c97de',
        linkHover: '#e90',
        focus: 'rgba(22, 115, 177, 0.25)',
        border: 'black',
        name: '#690',
        type: '#905',
        error: '#c00',
        baseBackground: '#151515',
        codeBackground: 'black',
        sidebarBackground: '#303030',
        ribbonBackground: '#e90',
        ribbonText: '#fff',
        // Based on default Prism theme
        codeBase: '#e9e9e9',
        codeComment: '#6d6d6d',
        codePunctuation: '#999',
        codeProperty: '#905',
        codeDeleted: '#905',
        codeString: '#690',
        codeInserted: '#690',
        codeOperator: '#9a6e3a',
        codeKeyword: '#1673b1',
        codeFunction: '#DD4A68',
        codeVariable: '#e90',
    },
};
